version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    container_name: pg12-bank
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"
    volumes:
      - pg12-bankdata:/var/lib/postgresql/data

volumes:
  pg12-bankdata:
